name: path_finding
description: A Dart path finding library
author: Connor Gray <connordbgray@gmail.com>
homepage: https://www.github.com/ConnorGray/path_finding
version: 0.2.1
dependencies:
  test: ">=0.12.5+1 <0.13.0"
  benchmark_harness: ">=1.0.0 <2.0.0"
